# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0641583598aa60084c129b120987cf70874d967bd0a25d5135c7738279a60cb382bf08377a296de30cf1f22d28eaac4c527b0da93f9468c0b3f3cced2f05a798

test:
  secret_key_base: 192c609be71a9ae383cce1974e248fd6d0b682fb2167ed840eed43a83ad66b284963ee22f3768ec7c35a789d7f10442fdb2e686320676b03758c7bbafa744116

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
